name: aerospace
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  lottie: ^3.0.0
  pin_code_fields: ^8.0.1
  permission_handler: ^11.4.0

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/