name: bhumeet_user
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  cupertino_icons: ^1.0.8
  geolocator: ^9.0.2
  google_maps_flutter: ^2.5.0
  flutter_masked_text2: ^0.9.1
  pin_code_fields: ^8.0.1
  get: ^4.6.5
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  #firebase
  





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/drone_image.jpg

 