// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmLf8lf5omvIlDUXJNP6fzhj4GTOb081Q',
    appId: '1:1061334575051:web:6ed20eafd23a499effb84e',
    messagingSenderId: '1061334575051',
    projectId: 'aerosystem-user',
    authDomain: 'aerosystem-user.firebaseapp.com',
    storageBucket: 'aerosystem-user.firebasestorage.app',
    measurementId: 'G-HTN1KLRPX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzodoq7QyUbvTVZgavdu2GUKZQAED_1NI',
    appId: '1:1061334575051:android:79d5a37605cf5f08ffb84e',
    messagingSenderId: '1061334575051',
    projectId: 'aerosystem-user',
    storageBucket: 'aerosystem-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXXKRn0ds3G0OCr1JbY8Fq3PThC5wZHKY',
    appId: '1:1061334575051:ios:16fea1a0ba836396ffb84e',
    messagingSenderId: '1061334575051',
    projectId: 'aerosystem-user',
    storageBucket: 'aerosystem-user.firebasestorage.app',
    androidClientId: '1061334575051-djkde9c2vu86p7anl1f5gjcnra35t60m.apps.googleusercontent.com',
    iosClientId: '1061334575051-envprbg213paj6jo2n3npsuk7q5n7sq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhumeetUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXXKRn0ds3G0OCr1JbY8Fq3PThC5wZHKY',
    appId: '1:1061334575051:ios:16fea1a0ba836396ffb84e',
    messagingSenderId: '1061334575051',
    projectId: 'aerosystem-user',
    storageBucket: 'aerosystem-user.firebasestorage.app',
    androidClientId: '1061334575051-djkde9c2vu86p7anl1f5gjcnra35t60m.apps.googleusercontent.com',
    iosClientId: '1061334575051-envprbg213paj6jo2n3npsuk7q5n7sq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhumeetUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmLf8lf5omvIlDUXJNP6fzhj4GTOb081Q',
    appId: '1:1061334575051:web:96e3b8c02882a76dffb84e',
    messagingSenderId: '1061334575051',
    projectId: 'aerosystem-user',
    authDomain: 'aerosystem-user.firebaseapp.com',
    storageBucket: 'aerosystem-user.firebasestorage.app',
    measurementId: 'G-Y3WZWWLKBE',
  );

}